### ISSUE TITLE
Always gets the SHA1 hash from en-us, even if downloading other languages

### ISSUE THREAD

**Issue by eudinaesis** [Technogeezer50/24H2_esd2iso#2]
Thanks so much for making this! For some reason, it always seems to get the SHA1 hash from the EN-US version, even if you're actually downloading another one.

See here:

Select a language for your Windows 11 ARM Professional ISO
Enter a Windows language tag (example: 'en-us'), or
     'p' to print the list of available languages, or
     'q' to exit the program without creating an ISO: de-de
Getting info on ESD from Microsoft
ESDURL : http://dl.delivery.mp.microsoft.com/filestreamingservice/files/4ba0241
7-fa20-4601-8e41-0472b5aed151/26100.1742.240909-0928.ge_release_svc_refresh_CLI
ENTCONSUMER_RET_A64FRE_en-us.esd
SHA1 : 4483ca4ad07f42a796d99d6c0820951a8494ec0a
SUCCESS
Downloading ESD from Microsoft                                                 Edition : Professional                                                         Language : de-de
Downloading Windows 11 Professional_de-de ESD file : 100.00%
ESD: /Users/pnorthup/Developer/24H2_esd2iso/26100.1742.240909-0928.ge_release_s
vc_refresh_CLIENTCONSUMER_RET_A64FRE_de-de.esd
SUCCESS
Validating download (this may take a minute or so)
[ERROR] ESD validation failed, error code 1
Expected hash = 4483ca4ad07f42a796d99d6c0820951a8494ec0a
        Calculated hash = 7db17a1adb2dc7aa16ad519967407da107a9583d
Program aborting

**Comment by eudinaesis** [comment]
Thanks!

**Comment by Technogeezer50** [comment]
You're welcome and thanks for reporting this. It was a misplaced space in the command that retrieves the hash value. For some reason the VMware command didn't throw a syntax error, but decided to silently default to en-us. 

Go figure.

I'm not blameless  - I should have caught this by trying languages other than en-us.
