### ISSUE TITLE
ISO created by the script identifies as Windows Server 2025

### ISSUE THREAD

**Issue by risa2000** [Technogeezer50/24H2_esd2iso#4]
Running the script with the latest Fusion Pro 13.6.0 (for personal use) produced an image:
26100.1742.240909-0928.ge_release_svc_refresh_CLIENTCONSUMER_RET_A64FRE_en-us.iso
which, when imported into Fusion create dialog identifies as Windows Server 2025
![Screenshot 2024-10-09 at 20 07 07](https://github.com/user-attachments/assets/91b03652-7cb4-43fd-9c21-f8c352874af7)
Continuing the create process, it offers several flavors of Windows Server 2025 for the VM.

**Comment by Technogeezer50** [comment]
This is not a problem with the script. It's a VMware Fusion problem.  Fusion does not recognize a Windows 11 ARM 24H2 ISO as Windows 11 when you drag and drop the ISO onto the "Choose the Installation Source" dialog (or click on the "Use another disc or disc image..." button.   Microsoft has changed something in their ESD distribution and VMware hasn't caught up to the changes to make their VM creation wizard work properly.

The same thing happens for ISOs created from UUPdump, by the way.  

See this thread in the Broadcom Fusion community: https://community.broadcom.com/vmware-cloud-foundation/discussion/windows-11-arm-24h2-installation-problems-workaround for instructions on how to work around this VMware Fusion problem.

I am closing this issue as it's up to VMware to make their wizard  work properly to support Windows 11 ARM 24H2.
