### ISSUE TITLE
vmw_esd2iso geturl didn't return a SHA1 hash for the desired edition/language Program aborting

### ISSUE THREAD

**Issue by baicaiyihao** [Technogeezer50/24H2_esd2iso#5]
```
Which Edition of Windows 11 ARM do you wish to download?
Enter 'p' to create a Professional Edition ISO
          (includes Professional and Home Editions), or
      'e' to create a Enterprise Edition ISO
          (includes Professional and Enterprise Editions), or
      'q' to exit the program without creating an ISO: p


Select a language for your Windows 11 ARM Professional ISO
Enter a Windows language tag (example: 'en-us'), or
     'p' to print the list of available languages, or
     'q' to exit the program without creating an ISO: en-us

Getting info on ESD from Microsoft
bsdtar: Error opening archive: Unrecognized archive format
ERROR: Error while extracting tar file: exit status 1
ERROR: Failed to get ESD url from Microsoft for Professional of language en-us
[ERROR] setupEsdDownload failed, error code 2
vmw_esd2iso geturl didn't return a SHA1 hash for the desired edition/language
Program aborting
```

**Comment by Technogeezer50** [comment]
The  following errors:
```
bsdtar: Error opening archive: Unrecognized archive format
ERROR: Error while extracting tar file: exit status 1
ERROR: Failed to get ESD url from Microsoft for Professional of language en-us
```

are being returned by the vmw_esd2iso tool built into Fusion.  That tool is finding problems with a file downloaded from Microsoft. 

Can you re-run the script and see if the error returns? Microsoft's download servers have shown that they're less than robust at times (perhaps when they're being updated???). I just re-ran the script  and find that it completes without error.

**Comment by baicaiyihao** [comment]
<img width="640" alt="image" src="https://github.com/user-attachments/assets/39e5c96a-d561-4278-9ce5-50bebcb5e4fe">

I used VM fusion to download successfully once before. But when I downloaded it again, an error occurred.

**Comment by Technogeezer50** [comment]
If Fusion isn't downloading the file, that means it's either a problem with Fusion's vmw_esd2iso utility (the same one that is used in 24H2_esd2iso), your network, or Microsoft's servers. If you've downloaded it successfully before, I'd rule out the utility and your network. My bet would be on Microsoft's servers given how they've behaved lately. The only way around that is to keep trying the download.

I'm downloading the Chinese (zh-cn) language ISO successfully using Fusion. 

I'm closing this issue as there's nothing that this script can do to compensate for problems with Fusion's utilities,  the network, or Microsoft's servers.  

If you want something that can compensate better for network problems, you may want to try my w11arm_esd2iso utillity found at https://github.com/Technogeezer50/esd2iso. It uses a different network transfer utility (the open source aria2c) which can provide some more robustness to network issues than the VMware tool vmw_esd2iso. 

But think twice before you go down that road.

You should know that:
* you will need to install some open source utilities from Homebrew or MacPorts to use w11arm_esd2iso. One of the design decisions I made for 24H2_esd2iso was to avoid the complexity of forcing users to install additional software. 
* the VMware network driver is not installed in the ISO created from w11arm_esd2iso. Again, this was a design decision for w11arm_esd2iso at the time it was written. 

See the [Unofficial VMware Fusion for Apple Silicon Companion Guide, revision 29 or later](https://community.broadcom.com/vmware-cloud-foundation/viewdocument/the-unofficial-fusion-for-apple-sil?CommunityKey=0c3a2021-5113-4ad1-af9e-018f5da40bc0&tab=librarydocuments) for more information on how to use Windows 11 ARM ISOs other than the ones generated by Fusion.
